---

#- include: mesos-source.yml
#  when: mesos_install_source is defined and mesos_install_source == True

- include: mesos-repo.yml
  when: mesos_install_source is defined and mesos_install_source == False

- include: zookeeper.yml
  when: mesos_install_source is defined and mesos_install_source == False

- include: mesos.yml
  when: mesos_install_source is defined and mesos_install_source == False
