---

#- include: mesos-source.yml
#  when: mesos_install_source is defined and mesos_install_source == True

- include: mesos.yml

- include: zookeeper.yml
  when: mesos_master is defined and mesos_master == True

- include: mesos-master.yml
  when: mesos_master is defined and mesos_master == True

- include: mesos-slave.yml
  when: mesos_slave is defined and mesos_slave == True
