---

- name: Install mesos-server Packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - git
    - language-pack-ja
    - mesos={{mesos_version}}-{{mesos_package_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
    - oracle-java8-installer
    - marathon
