---

- debug: msg="Zookeeper id is {{mesos_zookeeper_id}}"
- debug: msg="ipaddress is {{ mesos_interface_ipaddress }}"

- name: Add mesosphere APT key
  apt_key: keyserver=keyserver.ubuntu.com state=present id=E56151BF
  register: mesos_repo_installed

- name: Add mesosphere APT repository
  apt_repository: repo='deb {{ mesos_apt_url }} {{ansible_distribution_release|lower}} main' state=present
  register: mesos_repo_installed

- name: Add java APT repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Autoaccept license for Java8
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install mesos Packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - git
    - language-pack-ja
    - mesos={{mesos_version}}-{{mesos_package_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
    - oracle-java8-installer
    - marathon
