---

- name: Stop zookeeper
  template: src=zookeeper.override.j2
            dest=/etc/init/zookeeper.override
            owner=root group=root mode=0640
  notify: stop zookeeper

- name: Stop mesos-master
  template: src=mesos-master.override.j2
            dest=/etc/init/mesos-master.override
            owner=root group=root mode=0640
  notify: stop mesos-master

- name: Setup mesos zk
  template: src=mesos-zk.j2
            dest=/etc/mesos/zk
            owner=root group=root mode=0640
  notify: restart mesos-slave

- name: Setup mesos hostname
  template: src=mesos-hostname.j2
            dest=/etc/mesos-slave/hostname
            owner=root group=root mode=0640
  notify: restart mesos-slave

- name: Setup mesos ip
  template: src=mesos-ip.j2
            dest=/etc/mesos-slave/ip
            owner=root group=root mode=0640
  notify: restart mesos-slave
