---

mesos_install_source: False

mesos_base_url: "http://www.apache.org/dist/mesos/"
mesos_version: "0.28.0"

mesos_source_packages:
  - tar
  - curl
  - wget
  - git-core
  - openjdk-7-jdk
  - autoconf
  - libtool
  - build-essential
  - python-dev
  - python-boto
  - libcurl4-nss-dev
  - libsasl2-dev
  - libsasl2-modules
  - maven
  - libapr1-dev
  - libsvn-dev
  - language-pack-ja

mesos_apt_url: "http://repos.mesosphere.com/{{ ansible_distribution | lower }}"
mesos_version: "0.28.0"
mesos_package_version: "2.0.16"

mesos_servers: []

mesos_zookeeper_servers: []

mesos_quorum: 2
mesos_ip: '{{ ansible_eth1.ipv4.address }}'
mesos_hostname: '{{ ansible_eth1.ipv4.address }}'
mesos_cluster_name: 'Cluster01'

mesos_option_packages: []
