---

mesos_install_source: False

mesos_base_url: "http://www.apache.org/dist/mesos/"
mesos_version: "0.28.0"

mesos_source_packages:
  - tar
  - curl
  - wget
  - git
  - openjdk-7-jdk
  - autoconf
  - libtool
  - build-essential
  - python-dev
  - python-boto
  - libcurl4-nss-dev
  - libsasl2-dev
  - libsasl2-modules
  - maven
  - libapr1-dev
  - libsvn-dev
  - language-pack-ja

mesos_apt_url: "http://repos.mesosphere.com/{{ ansible_distribution | lower }}"
mesos_version: "0.25.0"
mesos_package_version: "0.2.70"

mesos_option_packages: []
